package com.example.herobattler

import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import com.example.herobattler.databinding.FragmentHowToPlayBinding
import com.example.herobattler.databinding.FragmentNewCharacterBinding

class NewCharacter : Fragment() {
    private var _binding: FragmentNewCharacterBinding? = null
    private val binding get() = _binding!!

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)


    }

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?): View? {
        //adapt also this name (the class will be autogenerated)
        _binding = FragmentNewCharacterBinding.inflate(inflater, container, false)
        return binding.root
    }

}